name: apiowl
description: "A new Flutter project."

version: 1.0.0+7

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  flutter_background_service_android: ^6.2.7
  shared_preferences: ^2.3.3
  device_info_plus: ^11.2.0
  permission_handler: ^11.3.1
  loader_overlay: ^4.0.3
  flutter_spinkit: ^5.2.1
  #disable_battery_optimization: ^1.1.1
  firebase_core: ^3.10.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  video_player: ^2.9.3
  interactive_media_ads: ^0.2.3+8
  flutter_secure_storage: ^9.2.4
  upi_pay: ^1.1.0
  flutter_svg: ^2.0.17



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/icons/